spring:
  application:
    name: log-monitoring

  profiles:
    default: local

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      open-in-view: false
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration/postgresql

  # kafka:
  #   consumer:
  #     group-id: log-processing-group
  #     auto-offset-reset: earliest
  #     enable-auto-commit: false
  #   producer:
  #     acks: all

server:
  port: 8080

# management:
#   endpoints:
#     web:
#       exposure:
#         include: health,info

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui

app:
  security:
    jwt:
      secret: ${JWT_SECRET:default-secret-key-that-must-be-very-long-and-secure-for-hmac-sha-256}
      expiration-ms: ${JWT_EXPIRATION_MS:86400000} # 24 hours
      refresh-token:
        prefix: "identity:refresh_token:"
        expiration-days: 7
