import type { ApiEnvelope } from "@/features/applications/application-types";

export type { ApiEnvelope };

export type AnomalyReport = {
  id: string;
  applicationId: string;
  alertId?: string | null;
  sourceType: string;
  ruleName: string;
  severity: string;
  status: string;
  title: string;
  summary?: string | null;
  hypothesis?: string | null;
  confidenceScore?: number | null;
  likelihoodLabel?: string | null;
  impactSummary?: string | null;
  investigationStepsJson?: string | null;
  recommendedActionsJson?: string | null;
  dimensionType?: string | null;
  dimensionValue?: string | null;
  metricGroup?: string | null;
  observedValue?: number | null;
  thresholdValue?: number | null;
  observedCount?: number | null;
  thresholdCount?: number | null;
  windowStart: string;
  windowEnd: string;
  evidencePayloadJson: string;
  aiTriggerRequested: boolean;
  aiTriggerReason?: string | null;
  aiStatus: string;
  aiModel?: string | null;
  aiPromptVersion?: string | null;
  aiStartedAt?: string | null;
  aiCompletedAt?: string | null;
  aiSummary?: string | null;
  aiConfidenceScore?: number | null;
  aiLikelihoodLabel?: string | null;
  aiRootCauseCandidatesJson?: string | null;
  aiRecommendedActionsJson?: string | null;
  aiInvestigationStepsJson?: string | null;
  aiResultJson?: string | null;
  aiRawResponseJson?: string | null;
  aiError?: string | null;
  createdAt: string;
  updatedAt: string;
};
